apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: pokermonitor-server
spec:
  selector:
    app: pokermonitor-server
  ports:
    - port: 50051
      targetPort: 50051
  type: LoadBalancer
  loadBalancerIP: 34.90.126.185