version: "3.8"
services: 
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "50051:50051"
  envoy:
    build:
      context: .
      dockerfile: envoy.dockerfile
    ports:
      - "9901:9901"
      - "10000:10000"
      - "8080:8080"